import type { NextPage, GetStaticProps, InferGetStaticPropsType } from 'next';
import dynamic from 'next/dynamic';
// import dynamic from 'next/dynamic';
import Head from 'next/head';
// import { useState } from 'react';

// import { request, query } from 'lib/datocms';
// Hooks
import { Store } from '@Hooks/useStore';

import Navigation from '@Components/navigation';
import HeroSection from '@Components/hero-section';
const HowWeWork = dynamic(() => import('@Components/how-we-work'));
const WhatWeOffer = dynamic(() => import('@Components/what-we-offer'));
const OurLittleStory = dynamic(() => import('@Components/our-little-story'));
const GetInTouch = dynamic(() => import('@Components/get-in-touch'));
const Footer = dynamic(() => import('@Components/footer'));

const Home: NextPage = ({
  data,
  language,
  languages,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  if (!data) {
    return <main>Sorry! This page not found.</main>;
  }

  // console.log(data, language, languages);

  return (
    <Store.Provider value={{ language, languages, data }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Navigation />
      <main>
        <HeroSection />
        <HowWeWork />
        <WhatWeOffer />
        <OurLittleStory />
        <GetInTouch />
      </main>
      <Footer />
    </Store.Provider>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async context => {
  // const data = await request({ query, variables: { locale: context.locale } });

  return {
    props: {
      data,
      language: context.locale,
      languages: context.locales,
    },
  };
};

const data = {
  en: 'welcome',
  ru: 'добро пожаловать',
  fi: 'terve tuloa',
};
